- name: Starting Wordpress Role
  hosts: all
  gather_facts: yes
  become: true
  roles:
          - update
          - python
          - mysql
          - php
          - nginx
          - wordpress
