- name: Installing MySql
  apt:
          name: mysql-server
- name: Copying my.cnf
  copy:
          src:  .my.cnf
          dest:  /root/.my.cnf   
#- name: Set the root password
#  mysql_user:
#          name: root
#          password: root
#          login_unix_socket: /var/run/mysqld/mysqld.sock       
- name: Creating wordpress DB
  mysql_db:
          login_unix_socket: /var/run/mysqld/mysqld.sock
          name: wordpress
          state: present
          login_user: root
          login_password: root
- name: Creating wpuser for wordpress db
  mysql_user:
          login_user: root
          login_password: root
          login_unix_socket: /var/run/mysqld/mysqld.sock
          name: wpuser
          password: password
          host: "%"
          priv:  "wordpress.*:ALL,GRANT"
